# Generated by Django 2.2 on 2019-04-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12)),
                ('hostname', models.CharField(max_length=50)),
                ('last_ip', models.GenericIPAddressField()),
                ('firmware', models.CharField(max_length=50)),
            ],
        ),
    ]
